version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    build: ./src/database/
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./src/database/:/app

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"

  app1:
    build: ./src/use_cases/use_case_gateway/service_adapter
    ports:
      - "5006:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  app2:
    build: ./src/use_cases/use_case_gateway/use_case
    ports:
      - "5007:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - app1

  react:
    build: ./src/client/react_js_app
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq 

  news:
    build: ./src/services/news_service
    volumes:
      - ./src/services/news_service:/app
    ports:
      - 5005:5000
    depends_on:
      - rabbitmq

  weather:
    build: ./src/services/weather_service
    volumes:
      - ./src/services/weather_service:/app
    ports:
      - 5002:5000
    depends_on:
      - rabbitmq

  maps:
    build: ./src/services/maps_service
    volumes:
      - ./src/services/maps_service:/app
    ports:
      - 5003:5003
    depends_on:
      - rabbitmq

  wisdom:
    build: ./src/services/wisdom_service
    volumes:
      - ./src/services/wisdom_service:/app
    ports:
      - 5004:5004
    depends_on:
      - rabbitmq

  stockmarket:
    build: ./src/services/stock_market_service
    volumes:
      - ./src/services/stock_market_service:/app
    ports:
      - 5001:5000
    depends_on:
      - rabbitmq