version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"