name: Python Continuous Integration

on: 
  push:
    branches:
      - main
    paths:
      - '**.py'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
      - name: Run Black formatter
        uses: psf/black@stable
        with:
          options: ''
      - name: Run Pytest
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
        run: |
          python -m pip install --upgrade pip
          pip install -r $(find . -name requirements.txt -type f -print | xargs dirname)/requirements.txt
          pytest   
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--no-verify'
          commit_message: 'refactor: auto-format python code'
          