name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '.github/workflows/python_ci.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - '.github/workflows/python_ci.yaml'
  workflow_dispatch:    

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Black formatter
        run: |
          black .
      - name: Run Pytest
        run: |
          pytest
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--no-verify'
          commit_message: 'refactor: auto-format python code'
                   