name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '.github/workflows/python_ci.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - '.github/workflows/python_ci.yaml'
  workflow_dispatch:    

permissions:
  contents: write

env:
  MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
  STOCK_MARKET_API_KEY: ${{ secrets.STOCK_MARKET_API_KEY }}
  STOCK_MARKET_SECRET_KEY: ${{ secrets.STOCK_MARKET_SECRET_KEY }}
  NYTIMES_API_KEY: ${{ secrets.NYTIMES_API_KEY }}
  NINJAS_API_KEY: ${{ secrets.NINJAS_API_KEY }}
  NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
  SPORTS_API_KEY: ${{ secrets.SPORTS_API_KEY }}
  CODING_API_KEY: ${{ secrets.CODING_API_KEY }}
  EVENTS_API_KEY: ${{ secrets.EVENTS_API_KEY }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          find . -name requirements.txt -exec pip install -r {} \;
      - name: Run Black formatter
        run: |
          black .
      - name: Run Pytest
        run: |
          pytest --cov 
      - name: Check coverage 
        run: |
          coverage report --fail-under=80
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--no-verify'
          commit_message: 'refactor: auto-format python code'
                   
