version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"

  app1:
    build: ./service_adapter
    ports:
      - "5001:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  app2:
    build: ./use_case
    ports:
      - "5002:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - app1
