version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"

  data_source:
    build: ./service_adapter
    ports:
      - "5006:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  producer:
    build: ./use_case
    ports:
      - "5007:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - data_source
    
  websocket:
    build: ./
    ports:
      - "5010:5010"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  react:
    build: ../src/client/react_js_app
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq 
